apiVersion: "v1"
kind: "List"
items:
  -
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      labels:
        provider: "fabric8"
        component: "heapster"
      name: "heapster2"
    spec:
      replicas: 1
      selector:
        provider: "fabric8"
        component: "heapster"
      template:
        metadata:
          labels:
            provider: "fabric8"
            component: "heapster"
        spec:
          containers:
            -
              args:
                - "-source=kubernetes:https://openshift-master1.bc.jonqe.lab.eng.bos.redhat.com:8443?auth=&insecure=true&useServiceAccount=true&kubeletHttps=false&kubeletPort=10255"
                - "-sink=influxdb:http://influxdb-monitoring:8086"
                - "--logtostderr=true"
                - "--vmodule=*=4"
              image: "kubernetes/heapster:v0.17.0"
              name: "heapster"
          serviceAccount: "heapster"
